---
- hosts: delirio, makis
  tasks:
    - name: copy pacman.conf
      file: src=files_root/etc/pacman.conf dest=/etc/pacman.conf
      become: true
      register: pacman
    - name: check infinality key
      command: pacman-key --list-sigs 962DDE58
      ignore_errors: true
      register: infinality_key_exists
    - name: add infinality key
      shell: pacman-key -r 962DDE58
      when: infinality_key_exists|failed
      become: true
    - name: sign infinality key
      shell: pacman-key --lsign-key 962DDE58
      when: infinality_key_exists|failed
      become: true
    - name: sync pacman dbs
      pacman: update_cache=yes
      become: true
      when: pacman.changed
    - name: install packages
      pacman: name={{ item }} state=present force=yes
      become: true
      with_items:
        - automake
        - pkg-config
        - mtr
        - rfkill
        - pass
        - time # for platform.sh sdk/git
        - python
        - python-pip # python3 builtin pip stripped?
        - ipython
        - python-pyflakes # for emacs python flycheck
        - freetype2-infinality-ultimate
        - fontconfig-infinality-ultimate
        - cairo-infinality-ultimate
        - jdk8-openjdk-infinality
        - dropbox
        - alsa-utils # for amixer
        - chromium
        - bind-tools # for dig
        - yaourt
        - tk
        - ack
        - aspell-en
        - aspell-el
        - chromium
        - dnsmasq
        - unrar
        - unzip
        - qemu
        - wireshark-qt
        - xterm
        - xorg-xprop
        - xorg-server-xephyr
    - name: install aur packages
      yaourt: name={{ item }} state=present
      with_items:
        - physlock
        - chromium-pepper-flash
        - gcolor3
        - thunderbird-enigmail
        - tor-browser-en
        - z-dir-jump-git
        - virtualbox-ext-oracle
    - name: put me in user groups
      user: name=danmilon groups=wheel,uucp,rfkill,users,kvm,wireshark,docker
    - name: copy stuff
      synchronize: src=files/ dest=/home/danmilon
    - name: copy root stuff
      become: true
      copy: src=files_root/ dest=/ owner=root group=root
    - name: link stuff
      file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
      with_items:
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/pubring.gpg', dest: '/home/danmilon/.gnupg/pubring.gpg' }
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/secring.gpg', dest: '/home/danmilon/.gnupg/secring.gpg' }
        - { src: 'hangman_r.jpg', dest: '/home/danmilon/Pictures/wallpaper1'}
        - { src: 'podilato_r.jpg', dest: '/home/danmilon/Pictures/wallpaper2'}
    - name: do templates
      template: src=templates/{{ item.path }}.j2 dest=/{{ item.path }} mode={{ item.mode|default('0644') }}
      become: true
      with_items:
        - { path: 'home/danmilon/.xrandr-home', mode: '0755' }
        - { path: 'home/danmilon/.xprofile' }
        - { path: 'home/danmilon/.config/qtile/config.py' }
        - { path: 'usr/local/bin/monitor-set-initial-mode', mode: '0755' }
        - { path: 'usr/local/bin/monitor-only-external', mode: '0755'}
    - name: enable systemd services
      systemd: name={{ item }} enabled=yes
      become: true
      with_items:
        - screenlock@danmilon
        - sshd
    - name: enable ntp
      command: timedatectl set-ntp true

# TODO: mkinitcpio.conf
