---
- hosts: delogo, makis
  tasks:
    - name: delete folders we dont like
      file: path=/home/danmilon/{{ item }} state=absent
      with_items:
        - Templates
        - Public
    - name: copy pacman.conf
      copy: src=files_root/etc/pacman.conf dest=/etc/pacman.conf
      become: true
      register: pacman
    - name: sync pacman dbs
      pacman: update_cache=yes
      become: true
      when: pacman.changed
    - name: install packages
      tags:
        - packages
      pacman: name={{ item }} state=present force=yes
      become: true
      with_items:
        - qtile
        - thunderbird-extension-enigmail
        - automake
        - pkg-config
        - mtr
        - pass
        - time # for platform.sh sdk/git
        - python
        - python-pip # python3 builtin pip stripped?
        - ipython
        - python-pyflakes # for emacs python flycheck
        - dropbox
        - alsa-utils # for amixer
        - chromium
        - bind-tools # for dig
        - yaourt
        - tk
        - ack
        - aspell-en
        - aspell-el
        - hunspell-el
        - chromium
        - dnsmasq
        - unrar
        - unzip
        - qemu
        - wireshark-qt
        - xterm
        - xorg-xprop
        - xorg-server-xephyr
        - vagrant
        - docker
        - virtualbox
        - virtualbox-host-modules-arch
        - dkms
        - gtk-recordmydesktop
        - smplayer
        - youtube-dl
        - flake8
        - python2-flake8
        - strace
        - file-roller
        - lib32-alsa-plugins
        - mesa-vdpau
        - lib32-sdl
        - lib32-libtheora
        - lib32-openal
        - wireless_tools
        - squashfs-tools
        - dhclient
        - scrot
        - ethtool
        - cpupower
        - tlp
        - libreoffice
        - parallel
        - ipcalc
        - tcpdump
        - whois
        - cups
        - nss-mdns
        - aws-cli
        - gdb
        - abs
        - openbsd-netcat
        - audacity
        - clementine
        - gst-plugins-base
        - gst-plugins-good
        - gst-plugins-bad
        - gst-plugins-ugly
        - gst-libav
        - transmission-gtk
        - gksu
        - android-udev
        - gparted
        - fzf
        - keybase
        - beets
        - python-requests # dep of beets
        - xf86-input-libinput
        - python-pyudev
        - lsof
        - compton
        - firefox-ublock-origin
        - ntfs-3g
        - markdown
        - intel-ucode
        - dnscrypt-proxy
        - httpie
        - ansible
        - sshfs
        - libva-intel-driver
        - recode
        - systemd-swap
        - xorg-xmodmap
        - xfce4-notifyd
    - name: install aur packages
      tags:
        - packages
      yaourt: name={{ item }} state=present
      with_items:
        - physlock
        - chromium-pepper-flash
        - gcolor3
        - tor-browser-en
        - z
        - virtualbox-ext-oracle
        - google-talkplugin
        - screen
        - go-mtpfs-git
        - android-sdk-platform-tools
        - android-bash-completion
        - thermald
        - firefox-extension-https-everywhere
        # the 1.0 extension itself is only as part of a -git package, which is
        # not signed. install extension via addons.firefox.org
        - passff-host
        - light
        - undistract-me-git
        ###################
        # emacs golang deps
        - godef-git
        - gocode-git
        ###################
    - name: install pip packages not available via packages
      pip: name={{ item }}
      become: true
      tags:
        - packages
      with_items:
        - pulsectl
    - name: install host specific pacman packages
      pacman: name={{ packages|default([]) }} state=present
      tags:
        - packages
    - name: copy stuff
      synchronize: src=files/ dest=/home/danmilon
    - name: copy root stuff
      become: true
      copy: src=files_root/ dest=/ owner=root group=root
    - name: link stuff
      file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
      with_items:
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/pubring.gpg', dest: '/home/danmilon/.gnupg/pubring.gpg' }
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/secring.gpg', dest: '/home/danmilon/.gnupg/secring.gpg' }
        - { src: 'hangman_r.jpg', dest: '/home/danmilon/Pictures/wallpaper1'}
        - { src: 'podilato_r.jpg', dest: '/home/danmilon/Pictures/wallpaper2'}
    - name: do templates
      template: src=templates/{{ item.path }}.j2 dest=/{{ item.path }} mode={{ item.mode|default('0644') }}
      become: true
      with_items:
        - { path: 'home/danmilon/.xprofile' }
        - { path: 'usr/local/bin/monitor-set-initial-mode', mode: '0755' }
        - { path: 'usr/local/bin/monitor-only-external', mode: '0755'}
        - { path: 'etc/default/tlp' }
    - name: enable systemd services
      systemd: name={{ item }} enabled=yes
      become: true
      with_items:
        - screenlock@danmilon.service
        - sshd.service
        - tlp.service
        - avahi-daemon.service
        - org.cups.cupsd.service
        - thermald.service
        - docker.service
        - dnscrypt-proxy.socket
        - systemd-swap.service
    - name: enable ntp
      command: timedatectl set-ntp true
      become: true
    - name: put me in user groups
      become: true
      user: name=danmilon groups=wheel,uucp,rfkill,users,kvm,wireshark,docker
    - name: put me in host-specific user groups
      become: true
      user:
        name=danmilon
        groups={{ extra_groups|default("")|join(",") }}
        append=yes
    - name: intel ucode boot entry
      become: true
      lineinfile:
        dest: /boot/loader/entries/arch.conf
        line: "initrd /intel-ucode.img"
        insertbefore: "^initrd /initramfs-linux.img$"
# TODO: mkinitcpio.conf
