---
- hosts: delogo, makis
  tasks:
    - name: delete folders we dont like
      file: path=/home/danmilon/{{ item }} state=absent
      with_items:
        - Templates
        - Public
    - name: copy pacman.conf
      copy: src=files_root/etc/pacman.conf dest=/etc/pacman.conf
      become: true
      register: pacman
      when: ansible_distribution == "Archlinux"
    - name: sync pacman dbs
      pacman: update_cache=yes
      become: true
      when: pacman.changed and ansible_distribution == "Archlinux"
    - name: add yum repositories
      tags:
        - packages
      yum_repository:
        name: slack
        description: Slack
        baseurl: "https://packagecloud.io/slacktechnologies/slack/fedora/21/$basearch"
        gpgcheck: true
        gpgkey: "https://slack.com/gpg/slack_pubkey.gpg"
        metadata_expire: "300"
        sslcacert: "/etc/pki/tls/certs/ca-bundle.crt"
      become: true
      when: ansible_distribution == "Fedora"
    - name: install external yum repos
      command: |
        dnf config-manager
        --add-repo
        {{ item.repo_url }}
      args:
        creates: "/etc/yum.repos.d/{{ item.file_name }}"
        warn: false
      become: true
      with_items:
        - repo_url: https://copr.fedorainfracloud.org/coprs/tofik/autorandr/repo/fedora-30/tofik-autorandr-fedora-30.repo
          file_name: _copr:copr.fedorainfracloud.org:jdoss:slack-repo.repo
        - repo_url: https://download.docker.com/linux/fedora/docker-ce.repo
          file_name: docker-ce.repo
      when: ansible_distribution == "Fedora"
    - name: install h264 yum repo
      command: dnf config-manager --set-enabled fedora-cisco-openh264
      args:
        warn: false
        creates: /etc/yum.repos.d/fedora-cisco-openh264.repo
      become: true
      when: ansible_distribution == "Fedora"
    - name: install rpmfusion repos
      command: dnf -y install {{ item.repo_url }}
      args:
        warn: false
        creates: "/etc/yum.repos.d/{{ item.file_name }}"
      become: true
      with_items:
        - repo_url: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-30.noarch.rpm
          file_name: rpmfusion-free.repo
        - repo_url: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-30.noarch.rpm
          file_name: rpmfusion-nonfree.repo
      when: ansible_distribution == "Fedora"
    - name: remove undesirable yum packages
      tags:
        - packages
      package:
        name:
          - PackageKit-command-not-found
        state: absent
      become: true
      when: ansible_distribution == "Fedora"
    - name: install packages
      tags:
        - packages
      package:
        name:
          - qtile
          - zsh
          - pass
          - zsh-syntax-highlighting
          - make
          - thunderbird
          - thunderbird-enigmail
          - automake
          - pkg-config
          - mtr
          - time
          - python3-ipython
          - alsa-utils
          - chromium
          - aspell-en
          - aspell-el
          - hunspell-el
          - dnsmasq
          - unzip
          - qemu
          - wireshark
          - xterm
          - xfce4-terminal
          - xorg-x11-server-Xephyr
          - youtube-dl
          - strace
          - file-roller
          - file-roller-nautilus
          - wireless-tools
          - squashfs-tools
          - scrot
          - ethtool
          - tlp
          - libreoffice
          - parallel
          - ipcalc
          - whois
          - cups
          - nss-mdns
          - awscli
          - gdb
          - nmap-ncat
          - tcpdump
          - audacity
          - clementine
          - transmission-gtk
          - gstreamer-plugins-base
          - gstreamer-plugins-good
          - gstreamer-plugins-bad-free
          - gparted
          - fzf
          - beets
          - python3-pyudev
          - lsof
          - compton
          - ntfs-3g
          - dnscrypt-proxy
          - httpie
          - fuse-sshfs
          - recode
          - xfce4-notifyd
          - entr
          - rlwrap
          - light
          - lightdm-gtk
          - plantuml
          - thermald
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - feh
          - lilypond
          - blueman
          - network-manager-applet
          - gpaste
          - ImageMagick
          - libjpeg-turbo-utils
          - redshift-gtk
          - trash-cli
          - git-annex
          - pwgen
          - python2-virtualenv
          - pavucontrol
          - htop
          - mozilla-openh264
          - gstreamer1-plugin-openh264
          - ffmpeg
          - gstreamer1-libav
          - lm_sensors
          - ipcalc
          - gimp
          - smplayer
          - mpv
          - socat
          - brasero
          - vlc
          - golang
          - httpie
          - dropbox
          - python3-black
          - lshw
          - docker-compose
          - glibc-static # fedora-only?
          - openssl-devel # fedora-only
          - kubernetes-client # fedora-only
          # unnecessary psh packages
          - dash
          - mosh
      become: true
    # Old Archlinux packages that we haven't found an alternative for Fedora.
    - name: install archlinux packages
      tags:
        - packages
      package:
        name:
          - python
          - python-pip # python3 builtin pip stripped?
          - python-pyflakes # for emacs python flycheck
          - bind-tools # for dig
          - ack
          - chromium
          - unrar
          - xorg-xprop
          - vagrant
          - docker
          - virtualbox
          - virtualbox-host-modules-arch
          - dkms
          - gtk-recordmydesktop
          - smplayer
          - flake8
          - python2-flake8
          - lib32-alsa-plugins
          - mesa-vdpau
          - lib32-sdl
          - lib32-libtheora
          - lib32-openal
          - dhclient
          - cpupower
          - gst-plugins-ugly
          - gst-libav
          - gksu
          - android-udev
          - keybase
          - python-requests # dep of beets
          - xf86-input-libinput
          - firefox-ublock-origin
          - markdown
          - intel-ucode
          - libva-intel-driver
        state: present
        force: yes
      become: true
      when: ansible_distribution == "Archlinux"
    - name: install AUR packages
      tags:
        - packages
      yaourt: name={{ item }} state=present
      with_items:
        - physlock
        - chromium-pepper-flash
        - gcolor3
        - tor-browser-en
        - z
        - virtualbox-ext-oracle
        - google-talkplugin
        - screen
        - go-mtpfs-git
        - android-sdk-platform-tools
        - android-bash-completion
        - firefox-extension-https-everywhere
        # the 1.0 extension itself is only as part of a -git package, which is
        # not signed. install extension via addons.firefox.org
        - passff-host
        - undistract-me-git
        ###################
        # emacs golang deps
        - godef-git
        - gocode-git
        ###################
      when: ansible_distribution == "Archlinux"
    - name: install pip packages not available via packages
      tags:
        - packages
      pip:
        name:
          - pulsectl
          - virtualenv
          - black
      become: true
    # Not made compatible with fedora.
    # - name: install host specific packages
    #   package:
    #     name: "{{ packages|default([]) }}"
    #   tags:
    #     - packages
    #   become: true
    - name: copy stuff
      synchronize: src=files/ dest=/home/danmilon
    - name: copy root stuff
      become: true
      copy: src=files_root/ dest=/ owner=root group=root
    - name: link stuff
      file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
      with_items:
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/pubring.gpg', dest: '/home/danmilon/.gnupg/pubring.gpg' }
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/secring.gpg', dest: '/home/danmilon/.gnupg/secring.gpg' }
        - { src: 'hangman_r.jpg', dest: '/home/danmilon/Pictures/wallpaper1'}
        - { src: 'podilato_r.jpg', dest: '/home/danmilon/Pictures/wallpaper2'}
    - name: do templates
      template: src=templates/{{ item.path }}.j2 dest=/{{ item.path }} mode={{ item.mode|default('0644') }}
      become: true
      with_items:
        - { path: 'usr/local/bin/monitor-set-initial-mode', mode: '0755' }
        - { path: 'usr/local/bin/monitor-only-external', mode: '0755'}
        - { path: 'etc/default/tlp' }
    - name: disable systemd services
      systemd:
        name: "{{ item }}"
        enabled: false
      with_items:
        - gdm.service
      become: true
    - name: enable systemd services
      systemd:
        name: "{{ item}}"
        enabled: true
      become: true
      with_items:
        - screenlock@danmilon.service
        - sshd.service
        - tlp.service
        - avahi-daemon.service
        - cups.service
        - thermald.service
        - docker.service
        - dnscrypt-proxy.socket
        - bluetooth.service
        - lightdm.service
        - systemd-timesyncd.service
    - name: enable ntp
      command: timedatectl set-ntp true
      become: true
    - name: put me in user groups
      become: true
      user: name=danmilon groups=wheel,users,kvm,wireshark,docker
    - name: put me in host-specific user groups
      become: true
      user:
        name=danmilon
        groups={{ extra_groups|default("")|join(",") }}
        append=yes
    - name: intel ucode boot entry
      become: true
      lineinfile:
        dest: /boot/loader/entries/arch.conf
        line: "initrd /intel-ucode.img"
        insertbefore: "^initrd /initramfs-linux.img$"
      when: ansible_distribution == "Archlinux"
