---
- hosts: delogo, makis, 192.168.1.187
  tasks:
    - name: delete folders we dont like
      file: path=/home/danmilon/{{ item }} state=absent
      with_items:
        - Templates
        - Public
    - name: install external yum repos
      command: |
        dnf config-manager
        --add-repo
        {{ item.repo_url }}
      args:
        creates: "/etc/yum.repos.d/{{ item.file_name }}"
        warn: false
      become: true
      with_items:
        - repo_url: https://download.docker.com/linux/fedora/docker-ce.repo
          file_name: docker-ce.repo
      when: ansible_distribution == "Fedora"
    - name: install h264 yum repo
      command: dnf config-manager --set-enabled fedora-cisco-openh264
      args:
        warn: false
        creates: /etc/yum.repos.d/fedora-cisco-openh264.repo
      become: true
      when: ansible_distribution == "Fedora"
    - name: remove undesirable yum packages
      tags:
        - packages
      package:
        name:
          - PackageKit-command-not-found
        state: absent
      become: true
      when: ansible_distribution == "Fedora"
    - name: install packages
      tags:
        - packages
      package:
        name:
          - zsh
          - pass
          - zsh-syntax-highlighting
          - make
          - automake
          - pkg-config
          - mtr
          - time
          - python3-ipython
          - alsa-utils
          - chromium
          - aspell-en
          - aspell-el
          - hunspell-el
          - dnsmasq
          - unzip
          - qemu
          - xterm
          - xfce4-terminal
          - youtube-dl
          - strace
          - squashfs-tools
          - ethtool
          - tlp
          - parallel
          - ipcalc
          - whois
          - awscli
          - gdb
          - nmap-ncat
          - tcpdump
          - lsof
          - dnscrypt-proxy
          - httpie
          - fuse-sshfs
          - recode
          - entr
          - rlwrap
          - light
          - plantuml
          - thermald
          - docker-ce
          - docker-ce-cli
          - containerd.io
          # - gpaste
          - ImageMagick
          - libjpeg-turbo-utils
          - trash-cli
          - git-annex
          - pwgen
          - pavucontrol
          - htop
          - mozilla-openh264
          - gstreamer1-plugin-openh264
          - ffmpeg-free
          - gstreamer1-libav
          - lm_sensors
          - ipcalc
          - socat
          - golang
          - httpie
          - python3-black
          - lshw
          - docker-compose
          - yubikey-manager
          - alacritty
          - fzf
          - emacs
          # ------------
          - glibc-static # fedora-only?
          - openssl-devel # fedora-only
          - kubernetes-client # fedora-only
          # unnecessary psh packages
          - dash
          - mosh
      become: true
    - name: install flatpak apps
      tags:
        - packages
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        remote: flathub
        method: system
      with_items:
          - com.dropbox.Client
          - com.slack.Slack
          - com.transmissionbt.Transmission
          - org.chromium.Chromium
          - org.clementine_player.Clementine
          - org.gnome.Extensions
          - org.gimp.GIMP
          - org.mozilla.Thunderbird
          - org.onlyoffice.desktopeditors
          - org.videolan.VLC
          - org.wireshark.Wireshark
          - us.zoom.Zoom
    # Not made compatible with fedora.
    # - name: install host specific packages
    #   package:
    #     name: "{{ packages|default([]) }}"
    #   tags:
    #     - packages
    #   become: true
    - name: copy stuff
      synchronize: src=files/ dest=/home/danmilon
    - name: copy root stuff
      become: true
      copy: src=files_root/ dest=/ owner=root group=root
    - name: link stuff
      file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
      with_items:
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/pubring.gpg', dest: '/home/danmilon/.gnupg/pubring.gpg' }
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/secring.gpg', dest: '/home/danmilon/.gnupg/secring.gpg' }
    - name: do templates
      template: src=templates/{{ item.path }}.j2 dest=/{{ item.path }} mode={{ item.mode|default('0644') }}
      become: true
      with_items: []
    - name: enable systemd services
      systemd:
        name: "{{ item}}"
        enabled: true
      become: true
      with_items:
        - sshd.service
        - tlp.service
        - avahi-daemon.service
        - cups.service
        - thermald.service
        - docker.service
        - dnscrypt-proxy.socket
        - gdm.service
        - systemd-timesyncd.service
    - name: set my user properties
      become: true
      user:
        name: danmilon
        groups:
          - wheel
          - users
          - kvm
          - docker
          - dialout
        # append groups, don't replace.
        append: true
        shell: /usr/bin/zsh
    - name: put me in host-specific user groups
      become: true
      user:
        name=danmilon
        groups={{ extra_groups|default("")|join(",") }}
        append=yes
    - name: intel ucode boot entry
      become: true
      lineinfile:
        dest: /boot/loader/entries/arch.conf
        line: "initrd /intel-ucode.img"
        insertbefore: "^initrd /initramfs-linux.img$"
      when: ansible_distribution == "Archlinux"
    - name: Configure available keyboard layouts in Gnome
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us'), ('xkb', 'gr')]"
        state: present
    - name: Tell gnome Caps lock is control
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['caps:ctrl_modifier']"
        state: present
    - name: Input source switch keybind
      community.general.dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-input-source"
        value: "['<Alt>Shift_L']"
        state: present
