---
- hosts: antonis, makis
  tasks:
    - name: install packages
      pacman: name={{ item }} state=present
      with_items:
        - rfkill
        # - dropbox aur
        - pass
    - name: put me in user groups
      user: name=danmilon groups=wheel,uucp,rfkill,users
    - name: copy stuff
      synchronize: src=files/ dest=/home/danmilon
    - name: copy root stuff
      become: true
      copy: src=files_root/ dest=/ owner=root group=root
    - name: link stuff
      file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
      with_items:
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/pubring.gpg', dest: '/home/danmilon/.gnupg/pubring.gpg' }
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/secring.gpg', dest: '/home/danmilon/.gnupg/secring.gpg' }
        - { src: 'hangman_r.jpg', dest: '/home/danmilon/Pictures/wallpaper1'}
        - { src: 'podilato_r.jpg', dest: '/home/danmilon/Pictures/wallpaper2'}
    - name: do templates
      template: src=templates/{{ item.path }}.j2 dest=/{{ item.path }} mode={{ item.mode|default('0644') }}
      become: true
      with_items:
        - { path: 'home/danmilon/.xrandr-home', mode: '0755' }
        - { path: 'home/danmilon/.xprofile' }
        - { path: 'usr/local/bin/set-initial-monitor-mode', mode: '0755' }
