---
- hosts: antonis, makis
  tasks:
    - name: copy pacman.conf
      synchronize: src=files_root/etc/pacman.conf dest=/etc/pacman.conf
      become: true
      register: pacman
    - name: add infinality key
      shell: pacman-key -r 962DDE58
      become: true
    - name: sign infinality key
      shell: pacman-key --lsign-key 962DDE58
      when: pacman.changed
    - name: sync pacman dbs
      pacman: update_cache=yes
      become: true
      when: pacman.changed
    - name: install packages
      pacman: name={{ item }} state=present force=yes
      become: true
      with_items:
        - rfkill
        - pass
        - time # for platform.sh sdk/git
        - ipython
        - python-pyflakes # for emacs python flycheck
        - freetype2-infinality-ultimate
        - fontconfig-infinality-ultimate
        - cairo-infinality-ultimate
        - jdk8-openjdk-infinality
        - dropbox
        - alsa-utils # for amixer
        - chromium
    - name: install aur packages
      pacman: name={{ item }} state=present
      become: true
      with_items:
        - physlock-git
    - name: enable screenlock for me
      systemd: name="screenlock@danmilon" enabled=yes
      become: true
    - name: put me in user groups
      user: name=danmilon groups=wheel,uucp,rfkill,users
    - name: copy stuff
      synchronize: src=files/ dest=/home/danmilon
    - name: copy root stuff
      become: true
      copy: src=files_root/ dest=/ owner=root group=root
    - name: link stuff
      file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
      with_items:
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/pubring.gpg', dest: '/home/danmilon/.gnupg/pubring.gpg' }
        - { src: '/home/danmilon/Documents/Dropbox/crutial/gpg/card/secring.gpg', dest: '/home/danmilon/.gnupg/secring.gpg' }
        - { src: 'hangman_r.jpg', dest: '/home/danmilon/Pictures/wallpaper1'}
        - { src: 'podilato_r.jpg', dest: '/home/danmilon/Pictures/wallpaper2'}
    - name: do templates
      template: src=templates/{{ item.path }}.j2 dest=/{{ item.path }} mode={{ item.mode|default('0644') }}
      become: true
      with_items:
        - { path: 'home/danmilon/.xrandr-home', mode: '0755' }
        - { path: 'home/danmilon/.xprofile' }
        - { path: 'home/danmilon/.config/qtile/config.py' }
        - { path: 'usr/local/bin/set-initial-monitor-mode', mode: '0755' }
