[tool.poetry]
name = "my-machines"
version = "0.1.0"
description = ""
authors = ["Dan Milon <i@danmilon.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ansible = "^7.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
